services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - traefik-network
  db:
    image: postgres:12
    ports:
      - 2024:5432
    networks:
      - traefik-network
    volumes:
      - micro-service-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - traefik-network

  adminer:
    image: adminer
    ports:
      - 2025:8080
    networks:
      - traefik-network
    depends_on:
      - db

volumes:
  micro-service-data:
  redis_data:

networks:
  traefik-network:
    name: traefik-network

